name: Terraform Deploy

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: Infrasctructure/

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: Infrasctructure/

      - name: Terraform Validate
        run: terraform validate
        working-directory: Infrasctructure/

      - name: Terraform Plan
        run: terraform plan
        working-directory: Infrasctructure/

      - name: Terraform Apply (Auto-approve)
        run: terraform apply -auto-approve
        working-directory: Infrasctructure/
